# Fichier de configuration pour Netlify

[build]
  # Commande pour construire le site (inutile pour un site statique simple)
  # command = "npm run build"
  # Dossier à publier
  publish = "/"

[[headers]]
  for = "/*"
  [headers.values]
    # Politique de Sécurité de Contenu (CSP)
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' https: data:; connect-src 'self' https://api.netlify.com;"
    # Autres en-têtes de sécurité recommandés
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"